### ISSUE TITLE
[Translation Tools] Several notices thrown

### ISSUE THREAD

**Issue by acharrex** [acharrex/magento-core-ce#3]
When I try to update translation files (Fast Checkout or Core) (on Magento CE 1.4.0.0):

![error](https://cloud.githubusercontent.com/assets/1983908/7017793/f8be7a9a-dcfc-11e4-98cc-9e66a02ab8a9.png)

My repos is up-to-date.

**Comment by Pchianese** [comment]
Hello,

The translation tool cannot know how to treat this string.
We have two solutions do do that: 
   1. Replace the translation string by <?php echo $this->__('Street Address %s', $_i) ?>
   2. Allow multiple definition when a variable is found in a translation string

The problem with the first solution is that we can't define a different translation for street address 1 and street address 2.

What did you think ?

**Comment by acharrex** [comment]
La meilleure solution est la première.

Je mettrais à jour tous les fichiers de traduction (sur l'ensemble des cores) lorsque je porterais les changements effectués pour les licences.

Par contre, je te laisse effectuer cette modification dans l'ensemble des templates billing/shipping sur tous les cores.

**Comment by Pchianese** [comment]
Ok merci pour ta validation
Je te tiens au jus

++,
Paolo

Date: Thu, 9 Apr 2015 12:11:27 -0700

**Comment by Pchianese** [comment]
J'ai mis à jour la version 1.4.0.0.
Peux-tu valider que tu ne rencontre plus le problème de array to string convertion ?
Ma configuration apache ne m'affiche pas les warnings.

Merci,
Paolo

**Comment by Pchianese** [comment]
Changements effectués sur la version 1.4.0.1
Les versions supérieures possédaient déjà cette modification

Je te laisse voir pour la suite mais ce problème ne devrait se poser que pour les versions 1.4.0.0 et 1.4.0.1

**Comment by acharrex** [comment]
T'as pushé tes modifs?

**Comment by Pchianese** [comment]
oui commité et pushé pardon.

**Comment by acharrex** [comment]
Ok top merci.
Je te redis.

**Comment by acharrex** [comment]
C'est ok, par contre, le warning présent dans l'arbre des répertoires est toujours présent.

**Comment by Pchianese** [comment]
Je regarde vite le problème

**Comment by Pchianese** [comment]
Je n'arrive pas à reproduire le problème.
La notice n'est pas affichée et pourtant j'ai mon paramètre error_reporting à E_ALL et 30719 dans le php.ini.

Peux-tu me dire quelles sont tes configurations ?

Merci

**Comment by acharrex** [comment]
J'ai ça (standard Xampp):

error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors=On

Le reste me semble assez classique.

Si tu n'arrives pas à afficher les erreurs, je peux la fixer moi.

**Comment by Pchianese** [comment]
J'ai appliqué exactement la même configuration et toujours aucune notice

Peux-tu en effet fixer ce problème toi ?

Merci,
Paolo

**Comment by acharrex** [comment]
C'est fait.

En ligne 136 du fichier "lib\Extension.php", il faut modifier le code:

{code}
$folder = $curPath . '/' . $element;
{code}

par:

{code}
if (!is_array($element)) {
    $folder = $curPath . '/' . $element;
} else {
    $folder = null;
}
{code}

Je vais l'appliquer le correctif sur toutes les branches.

**Comment by Pchianese** [comment]
Ok cool

J'ai bientôt fini le code permettant de centraliser le tout.
Peux-tu appliquer la modification uniquement sur la 1.4.0.0 et je te mettrai à jour pour demain les translation de chaque core depuis le repository scripts ?

Mais si tu veux tout finir ajd c'est toi qui voit.

**Comment by acharrex** [comment]
Je l'ai commité uniquement sur la 1.4.0.0.
Je suis en train de tester le fix de mon fix de mon fix de ce truc de licences, du coup, on a le temps :)

**Comment by Pchianese** [comment]
Oki alors je vais faire cette modification et te tiendrai informé quand tu pourras mettre à jour les traductions

**Comment by Pchianese** [comment]
Voilà.

J'ai mis à jour le script de création des cores pour créer un répertoire tools contenant la bonne version du translation tool

Afin de valider avant que je répercute les modifications appliquées au core CE-1.4.0.0, peux-tu mettre à jour le répertoire "scripts" et exécuter le script "setup_magento_cores.bat" pour l'extension le core 1.4.0.0 en entrant les données suivantes : 

Core version (if empty, all versions will be updated) : 1.4.0.0
Update from git? (Y, N) : Y
Generate databases? (Y, N) : N

Le generate databases = N te permettra de ne pas mettre à jour toute ta base afin de continuer tes tests sur les licenses.

Puis bien vérifier que tu n'ais pas d'erreur dans l'import et que le répertoire tools/translation existe avec tout son contenu ?

Si c'est bon de ton côté, je répliquerai les modifications (suppression du répertoire tools dans tous les cores)

Merci et bonne fin de soirée,
Paolo

**Comment by acharrex** [comment]
C'est relativement bizarre, car après avoir lancé le "setup_magento_cores.bat" qui est fait un "pull" de la 1.4.0.0, les logs de TortoiseGit m'indiquent bien que le dossier "tools/translation" a été supprimé, mais ce dernier ne l'a pas été réellement.

Je ne sais pas si c'est dû à la commande ajoutée au "setup_magento_cores.bat" ou si GIT à quelques soucis.

Par ailleurs, est-ce que tu veux créer un nouveau scripts BAT (ex. "create_script_symlinks.bat") pour créer le lien symbolique vers le répertoire "translation"?

**Comment by Pchianese** [comment]
Hello,

Oui c'est normal car le script met à jour (donc suppression du répertoire tools) puis fait un pull des données mais en effet pas un lien symbolique...

Je vais te mettre ça à jour

@+,
Paolo

Date: Fri, 10 Apr 2015 11:19:19 -0700

**Comment by Pchianese** [comment]
J'ai appliqué les modifications nécessaires et je ne cache pas que le symlink m'a posé passablement de problèmes.

1. Tu peux mettre à jour le dossier scripts
2. exécuter un update de tous les cores à l'aide du script setup_magento_cores.bat
   - Core version (if empty, all versions will be updated) : 
   - Update from git? (Y, N) : Y
   - Generate databases? (Y, N) : N
3. Exécuter le script create_script_symlinks.bat

Fais-moi savoir si tu rencontre des problèmes

**Comment by acharrex** [comment]
C'est ok pour moi.
Merci.

2015-04-11 0:17 GMT+02:00 Pchianese <notifications@github.com>:

**Comment by acharrex** [comment]
En fait, en voulant regénérer les fichiers de trad 1.4.0.0, je suis tombé sur ce problème:

![fireshot screen capture 052 - translator manager - ce-1400_salesids-dev_com_tools_translation](https://cloud.githubusercontent.com/assets/1983908/7100874/ccec6f94-e03a-11e4-8bc8-eeb2674c795d.png)

Il semble que dans cette configuration (utilisation d'un lien symbolique), l'outil s'ouvre d'un problème de chemin.

Si je clique, dans la zone centrale, sur le répertoire "app/code", et que je me rends jusqu'à un fichier de l'extension, l'erreur suivante est retournée:

```
file not exists : C:/xampp/htdocs/salesids/core/community/1.4.0.0/tools/translation/C:/xampp/htdocs/salesids/core/community/1.4.0.0/app/code/community/SalesIds/FastCheckout/Block/Adminhtml/Checkout/Agreement/Edit.php
```

Idem pour les autres fichiers.

**Comment by Pchianese** [comment]
Ok je vais voir tout ça
C'est en effet un enfer à résoudre ces problèmes de liens symboliques mais je devrais pouvoir résoudre ce problème

**Comment by Pchianese** [comment]
Je viens de mettre à jour l'outil de traduction.
N'hésites pas à revenir vers moi si tu rencontre encore des problèmes

**Comment by acharrex** [comment]
OKI merci je te redis.


2015-04-11 12:54 GMT+02:00 Pchianese <notifications@github.com>:

**Comment by acharrex** [comment]
OK pour moi
